export const homeObjOne  = {
    id: 'home',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine:'GET YOUR DREAM JOBS',
    headline: 'Cracking the coding interview with CampusX',
    description:'Prepare for a technical interview with tips and techniques and interviews questions from students who cracked the coding questions of companies like Google, Microsoft & SAP labs and shared their positive experience with CampusX',
    buttonLabel:'Get Started',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo  = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine:'Placement Program',
    headline: 'About This Program',
    description:'This course is tailor-made for students who are openly looking for new opportunities in Product – Based Companies. Students will learn DS and Algo, Web Development and CORE knowledge of computers which prominently feature in technical interviews.',
    buttonLabel:'Apply for the course',
    imgStart: true,
    img: require('../../images/svg-2.svg').default,
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree  = {
    id: 'courses',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine:'MOX @ CampusX',
    headline: 'The Mock Interview Series',
    description:'Simulate the real-world interview experience and prepare for the technical interviews well in advance',
    buttonLabel:'Register',
    imgStart: false,
    img: require('../../images/svg-5.svg').default,
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true,
};