export const authConstants = {
    GET_CURRENT_USER_SIGN_IN: 'GET_CURRENT_USER_SIGN_IN',
    USER_SIGN_UP_ERROR: 'USER_SIGN_IN_ERROR',
    USER_SIGN_UP_SUCCESSFUL: 'USER_SIGN_IN_SUCCESSFUL',
    USER_SIGN_UP_LOADING: 'USER_SIGN_IN_LOADING',
    USER_SIGN_IN_LOADING: 'USER_SIGN_IN_LOADING',
    USER_SIGN_IN_SUCCESSFUL: 'USER_SIGN_IN_SUCCESSFUL',
    USER_SIGN_IN_FAILURE: 'USER_SIGN_IN_FAILURE',
    CLEAR_ERROR_MESSAGE_STATE: 'CLEAR_ERROR_MESSAGE_STATE',
    USER_SIGN_OUT_LOADING: 'USER_SIGN_OUT_LOADING',
    USER_SIGN_OUT_SUCCESSFUL: 'USER_SIGN_OUT_SUCCESSFUL',
    USER_SIGN_OUT_FAILURE: 'USER_SIGN_OUT_FAILURE',
    USER_RESET_PASSWORD_BY_MAIL_LOADING: 'USER_RESET_PASSWORD_BY_MAIL_LOADING',
    USER_RESET_PASSWORD_BY_MAIL_SUCCESSFUL: 'USER_RESET_PASSWORD_BY_MAIL_SUCCESSFUL',
    USER_RESET_PASSWORD_BY_MAIL_FAILURE: 'USER_RESET_PASSWORD_BY_MAIL_FAILURE',
    USER_RESET_PASSWORD_BY_MAIL_CLEAR_STATE: 'USER_RESET_PASSWORD_BY_MAIL_CLEAR_STATE',
    USER_GOOGLE_SIGN_IN_LOADING: 'USER_GOOGLE_SIGN_IN_LOADING',
    USER_GOOGLE_SIGN_IN_SUCCESS: 'USER_GOOGLE_SIGN_IN_SUCCESS',
    USER_GOOGLE_SIGN_IN_FAILURE: 'USER_GOOGLE_SIGN_IN_FAILURE',
}

export const courseConstants = {
    GET_COURSES_GET_LOADING: 'GET_COURSES_GET_LOADING',
    GET_COURSES_GET_SUCCESS: 'GET_COURSES_GET_SUCCESS',
    GET_COURSES_GET_FAILURE: 'GET_COURSES_GET_FAILURE',
    GET_COURSE_CONTENT_LOADING: 'GET_COURSE_CONTENT_LOADING',
    GET_COURSE_CONTENT_SUCCESS: 'GET_COURSE_CONTENT_SUCCESS',
    GET_COURSE_CONTENT_FAILURE: 'GET_COURSE_CONTENT_FAILURE',
    GET_ENROLLED_COURSES_LOADING: 'GET_ENROLLED_COURSES_LOADING',
    GET_ENROLLED_COURSES_SUCCESS: 'GET_ENROLLED_COURSES_SUCCESS',
    GET_ENROLLED_COURSES_FAILURE: 'GET_ENROLLED_COURSES_FAILURE',
    CLEAR_COURSES_FROM_STATE: 'CLEAR_COURSES_FROM_STATE',
};

export const paymentConstants = {
    PAYMENT_LOADING: 'PAYMENT_LOADING',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    PAYMENT_FAILURE: 'PAYMENT_FAILURE',
};