export const authConstants = {
    GET_CURRENT_USER_SIGN_IN: 'GET_CURRENT_USER_SIGN_IN',
    USER_SIGN_UP_ERROR: 'USER_SIGN_IN_ERROR',
    USER_SIGN_UP_SUCCESSFUL: 'USER_SIGN_IN_SUCCESSFUL',
    USER_SIGN_UP_LOADING: 'USER_SIGN_IN_LOADING',
}